services:
  db:
    image: postgres:17.4
    volumes:
      - db_boilerplate_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_TEST_NAME:-boilerplate_test}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  server:
    image: 'boilerplate/api'
    build:
      context: .
      cache_from:
        - 'boilerplate/api'
    volumes:
      - ./app:/app
    ports:
      - ${SERVER_PORT:-5000}:5000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_boilerplate_test:
